# Generated by Django 5.2.5 on 2025-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('AM', '午前の部'), ('PM', '午後の部')], max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('grades', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
            ],
            options={
                'ordering': ['session', 'number'],
            },
        ),
    ]
